### ISSUE TITLE
Q: Click: toggle between zoom-to-fit and 1:1

### ISSUE THREAD

**Issue by atomGit** [darktrojan/betterimageviewer#12]
my understanding is that a primary click on the image is supposed to toggle between fit and 1:1, but this doesn't work - i assume the "1" icon in the tools overlay should do the same, but it also doesn't work

ref: https://12bytes.org/wp-content/uploads/witness-positions-1.gif

**Comment by Hexerin** [comment]
Can confirm that this feature has ceased to function.

**Comment by darktrojan** [comment]
There's something weird going on with Firefox 68. I don't understand it. Everything works fine again in 69.

**Comment by darktrojan** [comment]
… or I've broken it.

**Comment by darktrojan** [comment]
Okay, released a fixed version.
