### ISSUE TITLE
Request: Remove Scrollbar 

### ISSUE THREAD

**Issue by Fake-Cake** [darktrojan/betterimageviewer#2]
**Problem**:
The design chosen for the add-on is really beautiful and fits in with its purpose. BUT, the presence of a scroll bar in an image display really ruins the whole thing.
**Proposed solution:**
Remove the scroll bar.
Mouse dragging is just enough to move around a large image.

**Comment by darktrojan** [comment]
I agree, but I don't want to remove them entirely. I'm trying to borrow some nice semi-transparent scrollbars from the developer tools, but haven't had time to finish the job yet.

**Comment by Fake-Cake** [comment]
I have no clue if it's possible to make them appear only when hovering over their places. But that would be even better.
Meanwhile, you can at least add an option to remove them entirely for interested users.
