### ISSUE TITLE
Doesn't work in Firefox 94

### ISSUE THREAD

**Issue by regs01** [darktrojan/betterimageviewer#21]
Mozilla broke something again with their APIs. Panning doesn't work in FF94.

**Comment by Wassss** [comment]
Same for me drag image doesn't work in FF94.

**Comment by LaserRacer** [comment]
Yep, same issue here. I just came here to check if anyone else had posted it yet.

**Comment by Wassss** [comment]
New version that i make based on @wenereth-arkhilmor [Pull request](https://github.com/darktrojan/betterimageviewer/pull/20)
https://github.com/Wassss/betterimageviewer/releases

**Comment by darktrojan** [comment]
This is now fixed.

**Comment by irvinm** [comment]
All, I'm seeing a strange behavior with build 22 but before I write it up as a defect, I was wondering if anyone else is seeing any abnormal behavior with the initial state of the image (whether smaller than the viewport or not).

Example with smaller image:  https://upload.wikimedia.org/wikipedia/commons/e/eb/Ash_Tree_-_geograph.org.uk_-_590710.jpg

The image loads and looks like the "overflowingVertical" tag is already there and therefore the margin-top = 0 and the image is drawn at the top of the screen.  Once I click on the image, the viewport vs. image size check works fine, the tag is removed, and the image properly returns to being centered on the screen.

I see something similar with larger than viewport images but slightly different.

Pre-click:

![image](https://user-images.githubusercontent.com/979729/140391932-98e91fd9-8003-4e70-a8fb-d4c89de9aaeb.png)

Post-click:

![image](https://user-images.githubusercontent.com/979729/140391958-1237f043-dfcf-48cc-b9d7-c36b8bb4cd2a.png)
